"""
SentinelOTA Edge Gateway — Route: Releases & Manifest
"""

from __future__ import annotations

from typing import Any

from cryptography.hazmat.primitives import serialization
from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile
from fastapi.responses import FileResponse

from ..config import MANIFEST_FILE
from ..crypto import get_signing_key, signing_fingerprint_hex
from ..config import SIGNING_ALGORITHM, SIGNING_KEY_ID
from ..models import ReleaseCreatePayload
from ..release import (
    create_release_locked,
    latest_release_for_device_locked,
    manifest_for_release_locked as _manifest_for_release_locked,
)
from ..state import STATE, STATE_LOCK, gateway_snapshot, persist_state_locked
from ..utils import normalize_compatibility, normalize_device_type, utc_now_iso
from ..auth import require_write_auth

import json

router = APIRouter()

# ESP32 images are ~1-2 MB; 32 MB is a generous ceiling that still bounds the
# amount a single request can buffer in memory.
MAX_UPLOAD_BYTES = 32 * 1024 * 1024


# Real API key guard, imported directly so Depends() captures the actual
# function (see gateway/auth.py for why this must not be monkey-patched).
_require_write_auth = require_write_auth


@router.get('/api/releases')
def list_releases() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    return {'ok': True, 'releases': snapshot.get('releases', [])}


@router.post('/api/releases')
def create_release(payload: ReleaseCreatePayload, _auth: None = Depends(_require_write_auth)) -> dict[str, Any]:
    compatibility = normalize_compatibility(payload.compatible)

    try:
        with STATE_LOCK:
            release, manifest, pipeline = create_release_locked(
                version=payload.version,
                description=payload.description.strip() or 'Firmware release generated by OTA gateway.',
                changelog=payload.changelog.strip() or 'Security and reliability updates.',
                compatible=compatibility,
                source_file_path=payload.sourceFilePath,
                status='published',
            )
            STATE['updatedAt'] = utc_now_iso()
            persist_state_locked()
    except ValueError as error:
        message = str(error)
        status_code = 409 if 'already exists' in message.lower() else 400
        raise HTTPException(status_code=status_code, detail=message) from error

    return {'ok': True, 'release': release, 'manifest': manifest, 'pipeline': pipeline}


@router.post('/api/releases/upload')
async def upload_release(
    file: UploadFile = File(..., description='Compiled firmware .bin'),
    version: str = Form(...),
    description: str = Form('Firmware release uploaded from the OTA dashboard.'),
    changelog: str = Form('Security and reliability updates.'),
    compatible: str = Form(''),
    _auth: None = Depends(_require_write_auth),
) -> dict[str, Any]:
    """Publish a release directly from an uploaded firmware binary.

    This is the web-UI publish path: the browser sends the .bin as multipart
    form data, so no file has to pre-exist on the gateway's filesystem (which
    is unreachable from the browser, and is a separate container in Docker).
    """
    original_name = (file.filename or '').strip()
    if not original_name.lower().endswith('.bin'):
        raise HTTPException(status_code=400, detail='Firmware artifact must be a .bin file.')

    payload = await file.read()
    if not payload:
        raise HTTPException(status_code=400, detail='Uploaded firmware artifact is empty.')

    if len(payload) > MAX_UPLOAD_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f'Firmware exceeds the {MAX_UPLOAD_BYTES // (1024 * 1024)} MB upload limit.',
        )

    requested = [entry.strip() for entry in compatible.split(',') if entry.strip()]
    compatibility = normalize_compatibility(requested or None)

    try:
        with STATE_LOCK:
            release, manifest, pipeline = create_release_locked(
                version=version,
                description=description.strip() or 'Firmware release uploaded from the OTA dashboard.',
                changelog=changelog.strip() or 'Security and reliability updates.',
                compatible=compatibility,
                status='published',
                artifact_bytes=payload,
                artifact_label=f'upload:{original_name}',
            )
            STATE['updatedAt'] = utc_now_iso()
            persist_state_locked()
    except ValueError as error:
        message = str(error)
        status_code = 409 if 'already exists' in message.lower() else 400
        raise HTTPException(status_code=status_code, detail=message) from error

    return {'ok': True, 'release': release, 'manifest': manifest, 'pipeline': pipeline}


@router.get('/api/releases/latest')
def latest_release() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    releases = snapshot.get('releases', [])
    if not releases:
        raise HTTPException(status_code=404, detail='No release available.')

    return {'ok': True, 'release': releases[0], 'manifest': snapshot.get('manifest')}


@router.get('/releases/latest/manifest')
def get_manifest(
    device_id: str | None = Query(default=None),
    device_type: str | None = Query(default=None),
) -> Any:
    """Manifest for the caller.

    With `device_type` (or a `device_id` the gateway already knows), returns
    the newest release whose `compatible` list covers that architecture. This
    is what stops an ESP8266 being handed an ESP32 image — `compatible` was
    previously recorded on every release and never read.

    With no identifying parameter the global latest manifest is returned, so
    firmware built before this existed keeps working unchanged.
    """
    resolved_type = ''
    if device_type:
        resolved_type = normalize_device_type(device_type)
    elif device_id:
        with STATE_LOCK:
            known = STATE.get('devices', {}).get(str(device_id))
            resolved_type = str(known.get('arch', '')) if known else ''

    if resolved_type:
        with STATE_LOCK:
            release = latest_release_for_device_locked(resolved_type)
            manifest = _manifest_for_release_locked(release) if release else None

        if not manifest:
            raise HTTPException(
                status_code=404,
                detail=f'No release available for device type {resolved_type}.',
            )
        return manifest

    # Unidentified caller — legacy global behaviour.
    if MANIFEST_FILE.exists():
        return FileResponse(path=MANIFEST_FILE, media_type='application/json')

    snapshot = gateway_snapshot()
    manifest = snapshot.get('manifest')
    if not manifest:
        raise HTTPException(status_code=404, detail='No manifest available.')

    with open(MANIFEST_FILE, 'w', encoding='utf-8') as file:
        json.dump(manifest, file, indent=2)
    return manifest


@router.get('/releases/latest/public-key')
def get_public_signing_key() -> dict[str, Any]:
    public_key_pem = get_signing_key().public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode('utf-8')

    return {
        'algorithm': SIGNING_ALGORITHM,
        'keyId': SIGNING_KEY_ID,
        'fingerprint': signing_fingerprint_hex(),
        'publicKeyPem': public_key_pem,
    }
