"""
SentinelOTA Edge Gateway — Pydantic Request Models
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from .config import DEFAULT_COMPATIBILITY


class ReleaseCreatePayload(BaseModel):
    version: str
    description: str = 'Firmware release generated by OTA gateway.'
    changelog: str = 'Security and reliability updates.'
    compatible: list[str] = Field(default_factory=lambda: DEFAULT_COMPATIBILITY.copy())
    sourceFilePath: str | None = None


class DeploymentCreatePayload(BaseModel):
    releaseId: str | None = None
    deviceIds: list[str] | None = None


class PipelineRunPayload(BaseModel):
    releaseId: str | None = None
