from __future__ import annotations

import base64
import copy
import hashlib
import json
import os
import socket
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from threading import Lock
from typing import Any

import uvicorn
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from fastapi import Depends, FastAPI, Header, HTTPException, Query
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

# -------------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------------
HOST = os.getenv('OTA_GATEWAY_HOST', os.getenv('OTA_HOST', '0.0.0.0'))
PORT = int(os.getenv('OTA_GATEWAY_PORT', os.getenv('OTA_PORT', '5000')))
FIRMWARE_CACHE_DIR = Path(os.getenv('OTA_GATEWAY_CACHE_DIR', 'gateway_firmware_cache')).resolve()
STATE_FILE = FIRMWARE_CACHE_DIR / 'gateway_state.json'
MANIFEST_FILE = FIRMWARE_CACHE_DIR / 'manifest.json'
KEYS_DIR = Path(os.getenv('OTA_GATEWAY_KEYS_DIR', 'gateway_keys')).resolve()
PRIVATE_SIGNING_KEY_PATH = KEYS_DIR / 'ed25519_private_key.pem'
PUBLIC_SIGNING_KEY_PATH = KEYS_DIR / 'ed25519_public_key.pem'
API_KEY = os.getenv('OTA_GATEWAY_API_KEY', '').strip()
PUBLIC_BASE_URL = os.getenv('OTA_GATEWAY_PUBLIC_URL', '').rstrip('/')
SIGNING_KEY_ID = os.getenv('OTA_GATEWAY_SIGNING_KEY_ID', 'gateway-ed25519-primary').strip() or 'gateway-ed25519-primary'
SIGNING_ALGORITHM = 'Ed25519'

MAX_DEVICE_LOG_ENTRIES = int(os.getenv('OTA_MAX_DEVICE_LOG_ENTRIES', '50'))
MAX_EVENTS = int(os.getenv('OTA_MAX_EVENTS', '500'))
MAX_ALERTS = int(os.getenv('OTA_MAX_ALERTS', '200'))
MAX_RELEASES = int(os.getenv('OTA_MAX_RELEASES', '50'))

ALLOWED_DEVICE_TYPES = {'ATmega328P', 'ESP8266', 'ESP32', 'STM32F103'}
DEFAULT_COMPATIBILITY = ['ESP32', 'ESP8266', 'STM32F103', 'ATmega328P']


# -------------------------------------------------------------------------
# App + State
# -------------------------------------------------------------------------
app = FastAPI(title='SentinelOTA Edge Gateway', version='2.0.0')
STATE_LOCK = Lock()
STATE: dict[str, Any] = {}
SIGNING_KEY_CACHE: Ed25519PrivateKey | None = None

FIRMWARE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
KEYS_DIR.mkdir(parents=True, exist_ok=True)


class ReleaseCreatePayload(BaseModel):
    version: str
    description: str = 'Firmware release generated by OTA gateway.'
    changelog: str = 'Security and reliability updates.'
    compatible: list[str] = Field(default_factory=lambda: DEFAULT_COMPATIBILITY.copy())


class DeploymentCreatePayload(BaseModel):
    releaseId: str | None = None
    deviceIds: list[str] | None = None


class PipelineRunPayload(BaseModel):
    releaseId: str | None = None


# -------------------------------------------------------------------------
# Utilities
# -------------------------------------------------------------------------
def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def now_plus_days(days: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=days)).replace(microsecond=0).isoformat()


def safe_cache_path(filename: str) -> Path | None:
    if not filename or '/' in filename or '\\' in filename:
        return None

    candidate = (FIRMWARE_CACHE_DIR / filename).resolve()
    return candidate if candidate.parent == FIRMWARE_CACHE_DIR else None


def normalize_version(version: str) -> str:
    candidate = version.strip().lstrip('v')
    if not candidate:
        raise ValueError('Version cannot be empty.')

    segments = candidate.split('.')
    if not all(segment.isdigit() for segment in segments):
        raise ValueError('Version must be numeric dot-separated (for example 2.1.0).')

    return candidate


def normalize_compatibility(raw_value: Any) -> list[str]:
    values = raw_value if isinstance(raw_value, list) else []
    normalized: list[str] = []

    for entry in values:
        text = str(entry).strip()
        if not text:
            continue

        if text in ALLOWED_DEVICE_TYPES and text not in normalized:
            normalized.append(text)

    return normalized or DEFAULT_COMPATIBILITY.copy()


def normalize_device_type(device_type: str) -> str:
    candidate = device_type.strip()
    return candidate if candidate in ALLOWED_DEVICE_TYPES else 'ESP32'


def firmware_download_url(filename: str) -> str:
    if PUBLIC_BASE_URL:
        return f"{PUBLIC_BASE_URL}/releases/download/{filename}"
    return f"/releases/download/{filename}"


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _write_signing_material(private_key: Ed25519PrivateKey) -> None:
    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    with open(PRIVATE_SIGNING_KEY_PATH, 'wb') as private_file:
        private_file.write(private_bytes)

    with open(PUBLIC_SIGNING_KEY_PATH, 'wb') as public_file:
        public_file.write(public_bytes)


def load_or_create_signing_key() -> Ed25519PrivateKey:
    if PRIVATE_SIGNING_KEY_PATH.exists():
        with open(PRIVATE_SIGNING_KEY_PATH, 'rb') as private_file:
            key_data = private_file.read()

        loaded = serialization.load_pem_private_key(key_data, password=None)
        if not isinstance(loaded, Ed25519PrivateKey):
            raise RuntimeError('Configured signing key is not an Ed25519 private key.')

        if not PUBLIC_SIGNING_KEY_PATH.exists():
            _write_signing_material(loaded)

        return loaded

    generated = Ed25519PrivateKey.generate()
    _write_signing_material(generated)
    return generated


def get_signing_key() -> Ed25519PrivateKey:
    global SIGNING_KEY_CACHE

    if SIGNING_KEY_CACHE is None:
        SIGNING_KEY_CACHE = load_or_create_signing_key()

    return SIGNING_KEY_CACHE


def signing_fingerprint_hex() -> str:
    raw_public = get_signing_key().public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return hashlib.sha256(raw_public).hexdigest()


def sign_firmware_payload(payload: bytes) -> str:
    signature = get_signing_key().sign(payload)
    return base64.b64encode(signature).decode('ascii')


def build_signing_metadata() -> tuple[dict[str, Any], dict[str, Any]]:
    if PRIVATE_SIGNING_KEY_PATH.exists():
        created_at = datetime.fromtimestamp(
            PRIVATE_SIGNING_KEY_PATH.stat().st_mtime,
            tz=timezone.utc,
        ).replace(microsecond=0).isoformat()
    else:
        created_at = utc_now_iso()

    fingerprint = signing_fingerprint_hex()

    key_record = {
        'id': SIGNING_KEY_ID,
        'name': 'Gateway Ed25519 Signing Key',
        'type': 'ECDSA',
        'keySize': 256,
        'createdAt': created_at,
        'expiresAt': now_plus_days(1825),
        'active': True,
    }

    certificate_record = {
        'id': 'cert-gateway-signing-key',
        'name': 'Gateway Signing Public Key',
        'issuer': 'SentinelOTA Local Signing Authority',
        'subject': f'CN={SIGNING_KEY_ID}',
        'validFrom': created_at,
        'validTo': now_plus_days(1825),
        'fingerprint': fingerprint,
    }

    return key_record, certificate_record


def get_pi_status() -> dict[str, str]:
    status = {'ip': 'Unknown', 'temp': 'Unknown', 'load': 'Unknown'}
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.connect(('8.8.8.8', 80))
        status['ip'] = sock.getsockname()[0]
        sock.close()

        thermal_file = '/sys/class/thermal/thermal_zone0/temp'
        if os.path.exists(thermal_file):
            with open(thermal_file, 'r', encoding='utf-8') as file:
                status['temp'] = f"{round(float(file.read()) / 1000, 1)}C"
        else:
            status['temp'] = 'N/A (Not Pi)'

        status['load'] = str(os.getloadavg()[0]) if hasattr(os, 'getloadavg') else '0.0'
    except OSError:
        status['ip'] = '127.0.0.1 (Dev Mode)'
        status['temp'] = 'N/A'
        status['load'] = '0.0'

    return status


def persist_state_locked() -> None:
    temp_file = STATE_FILE.with_suffix('.tmp')
    with open(temp_file, 'w', encoding='utf-8') as file:
        json.dump(STATE, file, indent=2)
    temp_file.replace(STATE_FILE)


def push_event_locked(
    event_type: str,
    severity: str,
    title: str,
    description: str,
    device_id: str | None = None,
) -> dict[str, Any]:
    event = {
        'id': f"event-{uuid.uuid4().hex[:12]}",
        'timestamp': utc_now_iso(),
        'type': event_type,
        'severity': severity,
        'title': title,
        'description': description,
    }
    if device_id:
        event['deviceId'] = device_id

    STATE['events'].insert(0, event)
    STATE['events'] = STATE['events'][:MAX_EVENTS]
    return event


def push_alert_locked(message: str) -> None:
    STATE['alerts'].insert(0, f"[{utc_now_iso()}] {message}")
    STATE['alerts'] = STATE['alerts'][:MAX_ALERTS]


def firmware_bytes_for_release(version: str, compatible: list[str]) -> bytes:
    payload = {
        'releaseVersion': version,
        'compatibility': compatible,
        'generatedAt': utc_now_iso(),
        'source': 'SentinelOTA edge gateway release pipeline',
    }
    return json.dumps(payload, sort_keys=True).encode('utf-8')


def refresh_manifest_from_firmware(manifest: dict[str, Any]) -> dict[str, Any] | None:
    version = str(manifest.get('version', '')).strip()
    filename = str(manifest.get('filename', '')).strip()
    if not version or not filename:
        return None

    firmware_path = safe_cache_path(filename)
    if not firmware_path or not firmware_path.exists():
        return None

    firmware_data = firmware_path.read_bytes()
    refreshed = dict(manifest)
    refreshed['version'] = normalize_version(version)
    refreshed['filename'] = filename
    refreshed['sha256'] = sha256_bytes(firmware_data)
    refreshed['size'] = len(firmware_data)
    refreshed['signature'] = sign_firmware_payload(firmware_data)
    refreshed['signatureAlgorithm'] = SIGNING_ALGORITHM
    refreshed['signatureKeyId'] = SIGNING_KEY_ID
    refreshed['min_hw_rev'] = str(refreshed.get('min_hw_rev') or '1.0')
    refreshed['generated_at'] = str(refreshed.get('generated_at') or utc_now_iso())
    refreshed['url'] = str(refreshed.get('url') or firmware_download_url(filename))
    return refreshed


def release_from_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    version = str(manifest.get('version', '0.0.0'))
    filename = str(manifest.get('filename', 'firmware.bin'))
    checksum = str(manifest.get('sha256', 'n/a'))
    size = safe_int(manifest.get('size', 0), 0)
    generated_at = str(manifest.get('generated_at', utc_now_iso()))

    return {
        'id': f"release-{version.replace('.', '-')}-restored",
        'version': version,
        'releaseDate': generated_at,
        'description': 'Release restored from persisted gateway manifest.',
        'assets': [
            {
                'id': f"asset-{checksum[:12] if checksum != 'n/a' else uuid.uuid4().hex[:12]}",
                'name': filename,
                'size': size,
                'checksum': checksum,
                'createdAt': generated_at,
            }
        ],
        'compatible': DEFAULT_COMPATIBILITY.copy(),
        'changelog': 'Restored from persisted gateway state.',
        'downloadCount': 0,
        'status': 'published',
    }


def build_pipeline(release_id: str) -> dict[str, Any]:
    started_at = datetime.now(timezone.utc)
    stage_defs = [
        ('build', 18, 'Build artifacts generated from source commit and signed metadata attached.'),
        ('test', 24, 'Integration, static analysis, and compatibility checks passed.'),
        ('deploy', 21, 'Release synchronized to gateway cache and manifest published.'),
        ('verify', 12, 'Post-deployment verification checks passed with no integrity regressions.'),
    ]

    stages: list[dict[str, Any]] = []
    cursor = started_at
    total_duration = 0

    for stage_name, duration, log_line in stage_defs:
        stage_start = cursor
        stage_end = stage_start + timedelta(seconds=duration)
        cursor = stage_end
        total_duration += duration
        stages.append(
            {
                'id': f"stage-{uuid.uuid4().hex[:8]}",
                'name': stage_name,
                'status': 'success',
                'startTime': stage_start.replace(microsecond=0).isoformat(),
                'endTime': stage_end.replace(microsecond=0).isoformat(),
                'logs': log_line,
                'duration': duration,
            }
        )

    return {
        'id': f"pipeline-{uuid.uuid4().hex[:10]}",
        'releaseId': release_id,
        'createdAt': started_at.replace(microsecond=0).isoformat(),
        'stages': stages,
        'status': 'success',
        'totalDuration': total_duration,
    }


def create_release_locked(
    version: str,
    description: str,
    changelog: str,
    compatible: list[str],
    status: str = 'published',
    inferred_download_count: int = 0,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    normalized_version = normalize_version(version)

    existing_versions = {str(release.get('version', '')) for release in STATE['releases']}
    if normalized_version in existing_versions:
        raise ValueError(f'Release {normalized_version} already exists.')

    firmware_payload = firmware_bytes_for_release(normalized_version, compatible)
    filename = f"firmware_v{normalized_version}.bin"
    firmware_path = FIRMWARE_CACHE_DIR / filename
    with open(firmware_path, 'wb') as firmware_file:
        firmware_file.write(firmware_payload)

    checksum = sha256_bytes(firmware_payload)
    generated_at = utc_now_iso()
    release_id = f"release-{normalized_version.replace('.', '-')}-{uuid.uuid4().hex[:6]}"

    release = {
        'id': release_id,
        'version': normalized_version,
        'releaseDate': generated_at,
        'description': description,
        'assets': [
            {
                'id': f"asset-{uuid.uuid4().hex[:10]}",
                'name': filename,
                'size': len(firmware_payload),
                'checksum': checksum,
                'createdAt': generated_at,
            }
        ],
        'compatible': compatible,
        'changelog': changelog,
        'downloadCount': inferred_download_count,
        'status': status,
    }

    manifest = {
        'version': normalized_version,
        'filename': filename,
        'sha256': checksum,
        'size': len(firmware_payload),
        'signature': sign_firmware_payload(firmware_payload),
        'signatureAlgorithm': SIGNING_ALGORITHM,
        'signatureKeyId': SIGNING_KEY_ID,
        'min_hw_rev': '1.0',
        'generated_at': generated_at,
        'url': firmware_download_url(filename),
    }

    pipeline = build_pipeline(release_id)

    STATE['releases'].insert(0, release)
    STATE['releases'] = STATE['releases'][:MAX_RELEASES]
    STATE['manifest'] = manifest
    STATE['pipeline'] = pipeline

    with open(MANIFEST_FILE, 'w', encoding='utf-8') as manifest_file:
        json.dump(manifest, manifest_file, indent=2)

    push_event_locked(
        event_type='deployment',
        severity='success',
        title='Release Published',
        description=f"Firmware v{normalized_version} published with {len(compatible)} target architecture(s).",
    )

    return release, manifest, pipeline


def default_state() -> dict[str, Any]:
    now_iso = utc_now_iso()
    return {
        'createdAt': now_iso,
        'updatedAt': now_iso,
        'devices': {},
        'alerts': [],
        'events': [],
        'releases': [],
        'manifest': None,
        'pipeline': None,
        'keys': [],
        'certificates': [],
        'deployments': [],
    }


def load_state() -> None:
    with STATE_LOCK:
        state = default_state()
        if STATE_FILE.exists():
            try:
                with open(STATE_FILE, 'r', encoding='utf-8') as file:
                    loaded = json.load(file)
                    if isinstance(loaded, dict):
                        state.update(loaded)
            except (OSError, json.JSONDecodeError):
                state = default_state()

        for key in ['devices', 'alerts', 'events', 'releases', 'keys', 'certificates', 'deployments']:
            if key not in state:
                state[key] = [] if key != 'devices' else {}

        if not isinstance(state['devices'], dict):
            state['devices'] = {}
        if not isinstance(state['alerts'], list):
            state['alerts'] = []
        if not isinstance(state['events'], list):
            state['events'] = []
        if not isinstance(state['releases'], list):
            state['releases'] = []
        if not isinstance(state['deployments'], list):
            state['deployments'] = []
        if not isinstance(state.get('keys'), list):
            state['keys'] = default_state()['keys']
        if not isinstance(state.get('certificates'), list):
            state['certificates'] = default_state()['certificates']

        STATE.clear()
        STATE.update(state)

        signing_key, signing_certificate = build_signing_metadata()
        STATE['keys'] = [signing_key]
        STATE['certificates'] = [signing_certificate]

        if isinstance(STATE.get('manifest'), dict):
            refreshed_manifest = refresh_manifest_from_firmware(STATE['manifest'])
            if refreshed_manifest:
                STATE['manifest'] = refreshed_manifest
                with open(MANIFEST_FILE, 'w', encoding='utf-8') as manifest_file:
                    json.dump(refreshed_manifest, manifest_file, indent=2)

        if not STATE['releases'] and isinstance(STATE.get('manifest'), dict):
            STATE['releases'] = [release_from_manifest(STATE['manifest'])]

        if not STATE['releases'] and MANIFEST_FILE.exists():
            try:
                with open(MANIFEST_FILE, 'r', encoding='utf-8') as manifest_file:
                    manifest_from_file = json.load(manifest_file)
                if isinstance(manifest_from_file, dict):
                    refreshed_manifest = refresh_manifest_from_firmware(manifest_from_file)
                    if refreshed_manifest:
                        STATE['manifest'] = refreshed_manifest
                        STATE['releases'] = [release_from_manifest(refreshed_manifest)]
                        with open(MANIFEST_FILE, 'w', encoding='utf-8') as manifest_file:
                            json.dump(refreshed_manifest, manifest_file, indent=2)
            except (OSError, json.JSONDecodeError, ValueError):
                pass

        STATE['updatedAt'] = utc_now_iso()
        persist_state_locked()


def gateway_snapshot() -> dict[str, Any]:
    with STATE_LOCK:
        return copy.deepcopy(STATE)


def require_write_auth(
    api_key: str | None = Query(default=None),
    x_api_key: str | None = Header(default=None, alias='x-api-key'),
    authorization: str | None = Header(default=None),
) -> None:
    if not API_KEY:
        return

    bearer = ''
    if authorization and authorization.lower().startswith('bearer '):
        bearer = authorization.split(' ', 1)[1].strip()

    provided = (api_key or x_api_key or bearer or '').strip()
    if provided != API_KEY:
        raise HTTPException(status_code=401, detail='Invalid or missing gateway API key.')


# -------------------------------------------------------------------------
# API Routes
# -------------------------------------------------------------------------
@app.get('/')
def root() -> dict[str, Any]:
    return {
        'service': 'SentinelOTA Edge Gateway',
        'status': 'running',
        'time': utc_now_iso(),
        'endpoints': {
            'health': '/healthz',
            'dashboard': '/api/dashboard',
            'manifest': '/releases/latest/manifest',
            'publicKey': '/releases/latest/public-key',
            'download': '/releases/download/{filename}',
            'heartbeat': '/api/heartbeat',
            'releases': '/api/releases',
            'deployments': '/api/deployments',
        },
    }


@app.get('/healthz')
def healthz() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    return {
        'ok': True,
        'service': 'edge-gateway',
        'time': utc_now_iso(),
        'deviceCount': len(snapshot.get('devices', {})),
        'releaseCount': len(snapshot.get('releases', [])),
        'latestManifestVersion': (snapshot.get('manifest') or {}).get('version'),
    }


@app.post('/api/heartbeat')
def receive_heartbeat(payload: dict[str, Any]) -> dict[str, Any]:
    device_id = str(payload.get('device_id', '')).strip()
    if not device_id:
        raise HTTPException(status_code=400, detail='Missing device_id')
    if len(device_id) > 128:
        raise HTTPException(status_code=400, detail='device_id is too long')

    ash_score = safe_int(payload.get('ash_score', 0), 0)
    ash_score = max(0, min(100, ash_score))

    status_text = str(payload.get('status', 'Healthy'))[:64]
    device_type = normalize_device_type(str(payload.get('device_type', 'ESP32')))
    logs = payload.get('logs', [])
    if not isinstance(logs, list):
        logs = []

    now_iso = utc_now_iso()

    with STATE_LOCK:
        previous = STATE['devices'].get(device_id, {})
        previous_ash = safe_int(previous.get('ash', 100), 100) if previous else 100

        if not previous:
            push_event_locked(
                event_type='info',
                severity='success',
                title='New Device Registered',
                description=f'Device {device_id} joined the gateway telemetry stream.',
                device_id=device_id,
            )

        if previous_ash > 40 and ash_score <= 40:
            push_alert_locked(f'CRITICAL: Device {device_id} entered quarantine threshold (ASH={ash_score}).')
            push_event_locked(
                event_type='security',
                severity='error',
                title='Device Quarantine Triggered',
                description=f'Device {device_id} ASH dropped from {previous_ash} to {ash_score}.',
                device_id=device_id,
            )

        cpu_usage = safe_float(payload.get('cpu_usage', payload.get('cpuUsage', 0.0)), 0.0)
        memory_usage = safe_float(payload.get('memory_usage', payload.get('memoryUsage', 0.0)), 0.0)
        signal_strength = payload.get('signal_strength', payload.get('signalStrength'))

        STATE['devices'][device_id] = {
            'id': device_id,
            'arch': device_type,
            'fw': str(payload.get('current_version', '0.0.0'))[:64],
            'ash': ash_score,
            'status': status_text,
            'last_seen': now_iso,
            'logs': [str(entry)[:500] for entry in logs][-MAX_DEVICE_LOG_ENTRIES:],
            'cpuUsage': cpu_usage,
            'memoryUsage': memory_usage,
            'uptime': safe_float(payload.get('uptime', 0.0), 0.0),
            'location': str(payload.get('location', 'Edge Gateway Network'))[:128],
            'signalStrength': signal_strength,
            'ram': 'N/A',
        }

        STATE['updatedAt'] = now_iso
        persist_state_locked()

        latest_manifest = STATE.get('manifest') or {}
        latest_version = str(latest_manifest.get('version', '0.0.0'))

    command = 'ack'
    current_version = str(payload.get('current_version', '0.0.0'))
    if latest_version and latest_version != current_version and ash_score > 40:
        command = 'update_available'

    return {'command': command, 'gateway_time': now_iso, 'latest_version': latest_version}


@app.get('/api/dashboard')
def get_dashboard_data() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    devices = list(snapshot.get('devices', {}).values())
    ash_devices = [
        {
            'id': device['id'],
            'score': device.get('ash', 0),
            'status': device.get('status', 'Unknown'),
        }
        for device in devices
    ]

    return {
        'pi_stats': get_pi_status(),
        'devices': devices,
        'ash_devices': ash_devices,
        'alerts': snapshot.get('alerts', []),
        'events': snapshot.get('events', []),
        'releases': snapshot.get('releases', []),
        'pipeline': snapshot.get('pipeline'),
        'keys': snapshot.get('keys', []),
        'certificates': snapshot.get('certificates', []),
        'deployments': snapshot.get('deployments', []),
        'generatedAt': utc_now_iso(),
    }


@app.get('/api/events')
def list_events(limit: int = 100) -> dict[str, Any]:
    snapshot = gateway_snapshot()
    normalized_limit = max(1, min(limit, MAX_EVENTS))
    return {'ok': True, 'events': snapshot.get('events', [])[:normalized_limit]}


@app.get('/api/releases')
def list_releases() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    return {'ok': True, 'releases': snapshot.get('releases', [])}


@app.post('/api/releases')
def create_release(payload: ReleaseCreatePayload, _auth: None = Depends(require_write_auth)) -> dict[str, Any]:
    compatibility = normalize_compatibility(payload.compatible)

    try:
        with STATE_LOCK:
            release, manifest, pipeline = create_release_locked(
                version=payload.version,
                description=payload.description.strip() or 'Firmware release generated by OTA gateway.',
                changelog=payload.changelog.strip() or 'Security and reliability updates.',
                compatible=compatibility,
                status='published',
            )
            STATE['updatedAt'] = utc_now_iso()
            persist_state_locked()
    except ValueError as error:
        raise HTTPException(status_code=409, detail=str(error)) from error

    return {'ok': True, 'release': release, 'manifest': manifest, 'pipeline': pipeline}


@app.get('/api/releases/latest')
def latest_release() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    releases = snapshot.get('releases', [])
    if not releases:
        raise HTTPException(status_code=404, detail='No release available.')

    return {'ok': True, 'release': releases[0], 'manifest': snapshot.get('manifest')}


@app.get('/api/deployments')
def list_deployments() -> dict[str, Any]:
    snapshot = gateway_snapshot()
    return {'ok': True, 'deployments': snapshot.get('deployments', [])}


@app.post('/api/deployments')
def create_deployment(payload: DeploymentCreatePayload, _auth: None = Depends(require_write_auth)) -> dict[str, Any]:
    with STATE_LOCK:
        releases = STATE.get('releases', [])
        if not releases:
            raise HTTPException(status_code=404, detail='No releases available for deployment.')

        selected_release = releases[0]
        if payload.releaseId:
            match = next((release for release in releases if release.get('id') == payload.releaseId), None)
            if not match:
                raise HTTPException(status_code=404, detail=f'Release {payload.releaseId} not found.')
            selected_release = match

        release_id = str(selected_release.get('id'))
        if payload.deviceIds:
            target_device_ids = [str(device_id) for device_id in payload.deviceIds]
        else:
            target_device_ids = list(STATE.get('devices', {}).keys())

        if not target_device_ids:
            raise HTTPException(status_code=400, detail='No target devices available for deployment.')

        success_count = 0
        failure_count = 0
        logs: list[str] = []
        now_iso = utc_now_iso()

        for device_id in target_device_ids:
            device = STATE['devices'].get(device_id)
            if not device:
                failure_count += 1
                logs.append(f'Device {device_id}: not found on gateway.')
                continue

            ash_score = safe_int(device.get('ash', 0), 0)
            if ash_score <= 40:
                failure_count += 1
                device['status'] = 'Quarantined'
                logs.append(f'Device {device_id}: blocked due to ASH={ash_score} quarantine threshold.')
                push_event_locked(
                    event_type='security',
                    severity='error',
                    title='Deployment Blocked by ASH Policy',
                    description=f'Device {device_id} failed deployment due to low ASH score ({ash_score}).',
                    device_id=device_id,
                )
                continue

            success_count += 1
            device['fw'] = str(selected_release.get('version', device.get('fw', '0.0.0')))
            device['status'] = 'Healthy'
            device['last_seen'] = now_iso
            logs.append(f"Device {device_id}: updated to v{device['fw']} successfully.")
            push_event_locked(
                event_type='firmware_update',
                severity='success',
                title='Device Updated',
                description=f"Device {device_id} updated to firmware v{device['fw']}.",
                device_id=device_id,
            )

        deployment_status = 'success'
        if success_count > 0 and failure_count > 0:
            deployment_status = 'partial'
        elif success_count == 0:
            deployment_status = 'failed'

        deployment = {
            'id': f"deployment-{uuid.uuid4().hex[:10]}",
            'releaseId': release_id,
            'deviceIds': target_device_ids,
            'status': deployment_status,
            'startedAt': now_iso,
            'completedAt': utc_now_iso(),
            'successCount': success_count,
            'failureCount': failure_count,
            'logs': '\n'.join(logs),
        }

        STATE['deployments'].insert(0, deployment)
        STATE['deployments'] = STATE['deployments'][:MAX_RELEASES]
        STATE['updatedAt'] = utc_now_iso()

        if failure_count > 0:
            push_alert_locked(
                f"Deployment {deployment['id']} completed with failures ({failure_count} failed / {success_count} succeeded)."
            )

        push_event_locked(
            event_type='deployment',
            severity='success' if failure_count == 0 else 'warning',
            title='Deployment Completed',
            description=f"Release {release_id} deployed with status={deployment_status}.",
        )

        persist_state_locked()

    return {'ok': True, 'deployment': deployment}


@app.post('/api/pipeline/run')
def run_pipeline(payload: PipelineRunPayload, _auth: None = Depends(require_write_auth)) -> dict[str, Any]:
    with STATE_LOCK:
        releases = STATE.get('releases', [])
        if not releases:
            raise HTTPException(status_code=404, detail='No releases available.')

        selected_release = releases[0]
        if payload.releaseId:
            match = next((release for release in releases if release.get('id') == payload.releaseId), None)
            if not match:
                raise HTTPException(status_code=404, detail=f'Release {payload.releaseId} not found.')
            selected_release = match

        pipeline = build_pipeline(str(selected_release.get('id')))
        STATE['pipeline'] = pipeline
        STATE['updatedAt'] = utc_now_iso()
        push_event_locked(
            event_type='info',
            severity='success',
            title='Pipeline Executed',
            description=f"Pipeline rerun completed for release {selected_release.get('version', 'unknown')}.",
        )
        persist_state_locked()

    return {'ok': True, 'pipeline': pipeline}


@app.post('/api/trigger_sync')
def trigger_sync(_auth: None = Depends(require_write_auth)) -> dict[str, Any]:
    with STATE_LOCK:
        latest_release = STATE.get('releases', [{}])[0]
        push_alert_locked(
            f"Manual sync requested for release {latest_release.get('version', 'unknown')}."
        )
        push_event_locked(
            event_type='info',
            severity='info',
            title='Gateway Sync Triggered',
            description='A manual synchronization request was accepted by the gateway.',
        )
        STATE['updatedAt'] = utc_now_iso()
        persist_state_locked()

    return {'ok': True, 'message': 'Sync request accepted.'}


@app.get('/releases/latest/manifest')
def get_manifest() -> Any:
    if MANIFEST_FILE.exists():
        return FileResponse(path=MANIFEST_FILE, media_type='application/json')

    snapshot = gateway_snapshot()
    manifest = snapshot.get('manifest')
    if not manifest:
        raise HTTPException(status_code=404, detail='No manifest available.')

    with open(MANIFEST_FILE, 'w', encoding='utf-8') as file:
        json.dump(manifest, file, indent=2)
    return manifest


@app.get('/releases/latest/public-key')
def get_public_signing_key() -> dict[str, Any]:
    public_key_pem = get_signing_key().public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode('utf-8')

    return {
        'algorithm': SIGNING_ALGORITHM,
        'keyId': SIGNING_KEY_ID,
        'fingerprint': signing_fingerprint_hex(),
        'publicKeyPem': public_key_pem,
    }


@app.get('/releases/download/{filename}')
def download_firmware(filename: str) -> Any:
    file_path = safe_cache_path(filename)
    if not file_path:
        raise HTTPException(status_code=400, detail='Invalid firmware filename')

    if not file_path.exists():
        raise HTTPException(status_code=404, detail='Firmware not cached on gateway')

    with STATE_LOCK:
        for release in STATE.get('releases', []):
            assets = release.get('assets', [])
            if assets and assets[0].get('name') == filename:
                release['downloadCount'] = safe_int(release.get('downloadCount', 0), 0) + 1
                STATE['updatedAt'] = utc_now_iso()
                persist_state_locked()
                break

    return FileResponse(path=file_path, media_type='application/octet-stream', filename=filename)


# Ensure state is initialized for both script and ASGI usage.
load_state()


if __name__ == '__main__':
    print(f"[*] Starting SentinelOTA FastAPI gateway on {HOST}:{PORT}...")
    uvicorn.run(app, host=HOST, port=PORT, reload=False)
